### PR TITLE
Explore the cause for lack of token overlap

### PR DESCRIPTION
**Pull request by danich1**
This PR is a result of my braintrust on May 26, 2021. A question was raised on why there was a lack of token overlap between documents throughout the years of 2000-2021. Main conclusion is that information changes as science progresses and that numbers would improve if I were to implement a lemmatizer (process of changing words into their root form). Overall, I don't need to rigorously pursue this question as there are other avenues I've been advised to walk down (thesis committee mandate). Nonetheless, it is important to document so here is the PR.

Only file that needs to be checked is:
pubtator_subsample_experiment.ipynb

### CODE REVIEW

**Comment by nrosed** [comment]
This is very interesting! I'm surprised that even when you subsample to the same number of tokens, you don't get a better overlap. 
I'm just thinking out loud, so ignore if it doesn't make sense, but do you think you would get the same results if you only looked at high-frequency words?  I'm just wondering if it's driven by topic shift, the length of the document, or possibly that there are lots of new vocabulary each year in science.

**Review by nrosed — APPROVED** [review]

**Comment by danich1** [comment]
>I'm just thinking out loud, so ignore if it doesn't make sense, but do you think you would get the same results if you only looked at high-frequency words?

I wouldn't be surprised if it is a combination of topic shift and new vocabulary. I quickly generated the graph with high frequency tokens and unsurprisingly the amount of overlap improved. Overall conclusion is that topics shifts and new terms are concocted as scientists diversify their own research interests/projects.

**Comment by cgreene** [comment]
Are you pulling _words_ or _tokens_ when you pull an equal number and compare overlap?

**Comment by danich1** [comment]
>Are you pulling words or tokens when you pull an equal number and compare overlap?

Pulling individual tokens so each year has an equal number before I compare the overlap.

**Comment by nrosed** [comment]
one last question, I forget the composition of the cohort, but could this be driven by new journals being introduced? Would you still see this effect if you reduced your analysis to a single journal?

**Comment by cgreene** [comment]
I think that if you drew an equal number of _words_ you would get a better comparison. I can see why the results are what they are if this is sampling tokens. Years with more words have more draws for tokens. If you fix the word count, I think results would be different.

**Comment by danich1** [comment]
>one last question, I forget the composition of the cohort, but could this be driven by new journals being introduced? Would you still see this effect if you reduced your analysis to a single journal?

Good question. I ran the results and still get a similar looking figure. Due to github thinking my changes are too big I'm going to merge this PR now and then run the follow up experiment cgreene mentioned. Following merge if you want to discuss more feel free to slack me.

**Pull request merged**
