### PR TITLE
Generated new visualization on word vector distances

### PR DESCRIPTION
**Pull request by danich1**
This PR follows #9 which explored how alignment aides in word vector comparison. Now that word vectors have been aligned; the next question is how do words change through time? Each heatmap shows a year comparison given a token of interest. Ideally the goal is to see a spike in distances and then have the rest of the years stabilize. (CRISPR is a good example of this trend). Stop words are a great negative control to show that these kinds of words shouldn't change through time.

Side Note: Plydata is an awesome library

Main file to check is:
03_alignment_correction_calculations.ipynb

### CODE REVIEW

**Comment by miltondp** [comment]
I'm having issues visualizing the list of file changes. It says there are too many changes and it might not be possible to see in Github :(
If I go to individual commits, I can see some of them, but not sure if those are the final files. Any suggestions on how to proceed? I've never come across this before.

**Comment by danich1** [comment]
🤯 How did this PR become a infinite files change? LOL github broke. Basically my first commit apparently broke github's diff system. Cool....

Look at these links and send me feedback via comment system:
[03_alignment_correction_calculations.ipynb](https://nbviewer.jupyter.org/github/danich1/biovectors/blob/updated_distances/word2vec_decade_experiment/03_alignment_correction_calculations.ipynb)
[02_word2vec_decade_analysis.ipynb](https://nbviewer.jupyter.org/github/danich1/biovectors/blob/updated_distances/word2vec_decade_experiment/02_word2vec_decade_analysis.ipynb)

**Comment by miltondp** [comment]
Comments below by cell number.

> Look at these links and send me feedback via comment system:
> [03_alignment_correction_calculations.ipynb](https://nbviewer.jupyter.org/github/danich1/biovectors/blob/updated_distances/word2vec_decade_experiment/03_alignment_correction_calculations.ipynb)

* 2: `distance_file` might be created, from the beginning, as a Path object instead of a string, without the "/" separator.
* 2: not sure if that file you are saving as csv is going to be published for others to use, but if not (if it is just for internal usage), I find it better to use the pickle format for performance reasons.
* 2: you are sorting by "token" within the if statement, but not doing that within the else statement; not sure if that's intended.

* 9: it's a bit confusing to me what you are doing with `data_df` at the top, with two consecutives appends; append here is a method of a pd.DataFrame, right? don't you need to include `inplace=True` as well?

* 10: I would remove the path separator char ("/")

* 30: just thinking out loud, what's driving the bias? maybe with that insight you can pick the correct adjustment method

* 12: it's hard to quickly see the cells with the largest/smallest values; maybe use `vmin`/`vmax` (if using seaborn) to reduce the range of values in the colorbar? seems like the range goes from 0.02 to 0.25 more or less; the same is true for most of the following plots, except the one in cell 24 where you can clearly see a "cluster" of years where the distance goes up; this seems interesting if I'm not missing something: maybe the token underwent most of its semantic change between those blocks of years? looks like the token's meaninig is more or less homogeneous within two block of years (2016 on, and between 2008-2012), but between them is most different?

> [02_word2vec_decade_analysis.ipynb](https://nbviewer.jupyter.org/github/danich1/biovectors/blob/updated_distances/word2vec_decade_experiment/02_word2vec_decade_analysis.ipynb)

* 7: I think I read somewhere that it is better to use a context manager to open a file and save a pickle; but maybe the dump function already close the file handle.

**Review by miltondp — APPROVED** [review]
Done, finally! I left some questions and ideas, most are minor.

**Comment by danich1** [comment]
>2: not sure if that file you are saving as csv is going to be published for others to use, but if not (if it is just for internal usage), I find it better to use the pickle format for performance reasons.

Good point. I'll keep that in mind for the future, but I agree pickle would be faster to use.

>9: it's a bit confusing to me what you are doing with data_df at the top, with two consecutives appends; append here is a method of a pd.DataFrame, right? don't you need to include inplace=True as well?

This was a hack where I needed to run a long job but needed results before my committee meeting. Was suppose to remove the appends but forgot. 

>30: just thinking out loud, what's driving the bias? maybe with that insight you can pick the correct adjustment method

Great question. It seems to be model bias, but I honestly don't know. Have a future approach that will model the word vector variance, so hopefully I can get back to answering this question in a future update.

>12: it's hard to quickly see the cells with the largest/smallest values; maybe use vmin/vmax (if using seaborn) to reduce the range of values in the colorbar? seems like the range goes from 0.02 to 0.25 more or less; the same is true for most of the following plots, except the one in cell 24 where you can clearly see a "cluster" of years where the distance goes up; this seems interesting if I'm not missing something: maybe the token underwent most of its semantic change between those blocks of years? looks like the token's meaninig is more or less homogeneous within two block of years (2016 on, and between 2008-2012), but between them is most different?

Well I purposely let the heatmap be that way to show that these types of words don't move very much. The largest value is 0.27 but that's a small detail compared to the global message that stop words don't move drastically through time.Also, yes you are correct that for this token it remains homogeneous after an early shift throughout the years.

**Pull request merged**
